// Do not edit: file generated by reactGen

package todoapp

import "github.com/myitcv/gopherjs/react"

func (p *TodoAppDef) SetState(s TodoAppState) {
	p.ComponentDef.SetState(s)
}

func (p *TodoAppDef) State() TodoAppState {
	return p.ComponentDef.State().(TodoAppState)
}

func (p TodoAppState) IsState() {}

func (p *TodoAppDef) GetInitialStateIntf() react.State {
	return TodoAppState{}
}
