// Code generated by reactGen. DO NOT EDIT.

package react

// ButtonProps defines the properties for the <button> element
type ButtonProps struct {
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTMLDef
	ID                      string
	Key                     string
	OnChange                func(e *SyntheticEvent)
	OnClick                 func(e *SyntheticMouseEvent)
	Role                    string
	Style                   *CSS
	Type                    string
}

func (b *ButtonProps) assign(v *_ButtonProps) {

	v.ClassName = b.ClassName

	v.DangerouslySetInnerHTML = b.DangerouslySetInnerHTML

	if b.ID != "" {
		v.ID = b.ID
	}

	if b.Key != "" {
		v.Key = b.Key
	}

	v.OnChange = b.OnChange

	v.OnClick = b.OnClick

	v.Role = b.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	v.Style = b.Style.hack()

	v.Type = b.Type

}
