// Code generated by reactGen. DO NOT EDIT.

package react

// MainProps are the props for a <main> component
type MainProps struct {
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTML
	DataSet
	ID  string
	Key string

	OnChange
	OnClick

	Ref
	Role  string
	Style *CSS
}

func (m *MainProps) assign(v *_MainProps) {

	v.ClassName = m.ClassName

	v.DangerouslySetInnerHTML = m.DangerouslySetInnerHTML

	if m.DataSet != nil {
		for dk, dv := range m.DataSet {
			v.o.Set("data-"+dk, dv)
		}
	}

	if m.ID != "" {
		v.ID = m.ID
	}

	if m.Key != "" {
		v.Key = m.Key
	}

	if m.OnChange != nil {
		v.o.Set("onChange", m.OnChange.OnChange)
	}

	if m.OnClick != nil {
		v.o.Set("onClick", m.OnClick.OnClick)
	}

	if m.Ref != nil {
		v.o.Set("ref", m.Ref.Ref)
	}

	v.Role = m.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	v.Style = m.Style.hack()

}
