// Code generated by reactGen. DO NOT EDIT.

package react

// SpanProps defines the properties for the <p> element
type SpanProps struct {
	ID                      string
	Key                     string
	ClassName               string
	Role                    string
	OnChange                func(e *SyntheticEvent)
	OnClick                 func(e *SyntheticMouseEvent)
	DangerouslySetInnerHTML *DangerousInnerHTMLDef
}

func (s *SpanProps) assign(v *_SpanProps) {

	if s.ID != "" {
		v.ID = s.ID
	}

	if s.Key != "" {
		v.Key = s.Key
	}

	v.ClassName = s.ClassName

	v.Role = s.Role

	v.OnChange = s.OnChange

	v.OnClick = s.OnClick

	v.DangerouslySetInnerHTML = s.DangerouslySetInnerHTML

}
