// Code generated by reactGen. DO NOT EDIT.

package react

// LabelProps defines the properties for the <label> element
type LabelProps struct {
	ID                      string
	Key                     string
	ClassName               string
	Role                    string
	Style                   *CSS
	OnChange                func(e *SyntheticEvent)
	OnClick                 func(e *SyntheticMouseEvent)
	DangerouslySetInnerHTML *DangerousInnerHTMLDef
	For                     string
}

func (l *LabelProps) assign(v *_LabelProps) {

	if l.ID != "" {
		v.ID = l.ID
	}

	if l.Key != "" {
		v.Key = l.Key
	}

	v.ClassName = l.ClassName

	v.Role = l.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	v.Style = l.Style.hack()

	v.OnChange = l.OnChange

	v.OnClick = l.OnClick

	v.DangerouslySetInnerHTML = l.DangerouslySetInnerHTML

	v.For = l.For

}
