// Code generated by reactGen. DO NOT EDIT.

package react

// AProps defines the properties for the <a> element
type AProps struct {
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTML
	DataSet
	Href string
	ID   string
	Key  string

	OnChange
	OnClick

	Ref
	Role   string
	Style  *CSS
	Target string
	Title  string
}

func (a *AProps) assign(_v *_AProps) {

	_v.ClassName = a.ClassName

	_v.DangerouslySetInnerHTML = a.DangerouslySetInnerHTML

	if a.DataSet != nil {
		for dk, dv := range a.DataSet {
			_v.o.Set("data-"+dk, dv)
		}
	}

	_v.Href = a.Href

	if a.ID != "" {
		_v.ID = a.ID
	}

	if a.Key != "" {
		_v.Key = a.Key
	}

	if a.OnChange != nil {
		_v.o.Set("onChange", a.OnChange.OnChange)
	}

	if a.OnClick != nil {
		_v.o.Set("onClick", a.OnClick.OnClick)
	}

	if a.Ref != nil {
		_v.o.Set("ref", a.Ref.Ref)
	}

	_v.Role = a.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	_v.Style = a.Style.hack()

	_v.Target = a.Target

	_v.Title = a.Title

}
