// Code generated by reactGen. DO NOT EDIT.

package react

// UlProps defines the properties for the <ul> element
type UlProps struct {
	ID                      string
	Key                     string
	ClassName               string
	Role                    string
	Style                   *CSS
	OnChange                func(e *SyntheticEvent)
	OnClick                 func(e *SyntheticMouseEvent)
	DangerouslySetInnerHTML *DangerousInnerHTMLDef
}

func (u *UlProps) assign(v *_UlProps) {

	if u.ID != "" {
		v.ID = u.ID
	}

	if u.Key != "" {
		v.Key = u.Key
	}

	v.ClassName = u.ClassName

	v.Role = u.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	v.Style = u.Style.hack()

	v.OnChange = u.OnChange

	v.OnClick = u.OnClick

	v.DangerouslySetInnerHTML = u.DangerouslySetInnerHTML

}
