// Code generated by reactGen. DO NOT EDIT.

package react

// InputProps defines the properties for the <input> element
type InputProps struct {
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTMLDef
	DefaultValue            string
	ID                      string
	Key                     string
	OnChange                func(e *SyntheticEvent)
	OnClick                 func(e *SyntheticMouseEvent)
	Placeholder             string
	Role                    string
	Style                   *CSS
	Type                    string
	Value                   string
}

func (i *InputProps) assign(v *_InputProps) {

	v.ClassName = i.ClassName

	v.DangerouslySetInnerHTML = i.DangerouslySetInnerHTML

	if i.DefaultValue != "" {
		v.DefaultValue = i.DefaultValue
	}

	if i.ID != "" {
		v.ID = i.ID
	}

	if i.Key != "" {
		v.Key = i.Key
	}

	v.OnChange = i.OnChange

	v.OnClick = i.OnClick

	v.Placeholder = i.Placeholder

	v.Role = i.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	v.Style = i.Style.hack()

	v.Type = i.Type

	v.Value = i.Value

}
