// Code generated by reactGen. DO NOT EDIT.

package react

// CodeProps defines the properties for the <code> element
type CodeProps struct {
	ID                      string
	Key                     string
	ClassName               string
	Role                    string
	OnChange                func(e *SyntheticEvent)
	OnClick                 func(e *SyntheticMouseEvent)
	DangerouslySetInnerHTML *DangerousInnerHTMLDef
}

func (c *CodeProps) assign(v *_CodeProps) {

	if c.ID != "" {
		v.ID = c.ID
	}

	if c.Key != "" {
		v.Key = c.Key
	}

	v.ClassName = c.ClassName

	v.Role = c.Role

	v.OnChange = c.OnChange

	v.OnClick = c.OnClick

	v.DangerouslySetInnerHTML = c.DangerouslySetInnerHTML

}
