// Code generated by reactGen. DO NOT EDIT.

package react

// InputProps defines the properties for the <input> element
type InputProps struct {
	ID                      string
	Key                     string
	ClassName               string
	Role                    string
	OnChange                func(e *SyntheticEvent)
	OnClick                 func(e *SyntheticMouseEvent)
	DangerouslySetInnerHTML *DangerousInnerHTMLDef
	Placeholder             string
	Type                    string
	Value                   string
	DefaultValue            string
}

func (i *InputProps) assign(v *_InputProps) {

	if i.ID != "" {
		v.ID = i.ID
	}

	if i.Key != "" {
		v.Key = i.Key
	}

	v.ClassName = i.ClassName

	v.Role = i.Role

	v.OnChange = i.OnChange

	v.OnClick = i.OnClick

	v.DangerouslySetInnerHTML = i.DangerouslySetInnerHTML

	v.Placeholder = i.Placeholder

	v.Type = i.Type

	v.Value = i.Value

	if i.DefaultValue != "" {
		v.DefaultValue = i.DefaultValue
	}

}
