// Code generated by reactGen. DO NOT EDIT.

package react

// TextAreaProps defines the properties for the <textarea> element
type TextAreaProps struct {
	ID                      string
	Key                     string
	ClassName               string
	Role                    string
	Style                   *CSS
	OnChange                func(e *SyntheticEvent)
	OnClick                 func(e *SyntheticMouseEvent)
	DangerouslySetInnerHTML *DangerousInnerHTMLDef
	Placeholder             string
	Value                   string
	DefaultValue            string
}

func (t *TextAreaProps) assign(v *_TextAreaProps) {

	if t.ID != "" {
		v.ID = t.ID
	}

	if t.Key != "" {
		v.Key = t.Key
	}

	v.ClassName = t.ClassName

	v.Role = t.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	v.Style = t.Style.hack()

	v.OnChange = t.OnChange

	v.OnClick = t.OnClick

	v.DangerouslySetInnerHTML = t.DangerouslySetInnerHTML

	v.Placeholder = t.Placeholder

	v.Value = t.Value

	if t.DefaultValue != "" {
		v.DefaultValue = t.DefaultValue
	}

}
