// Code generated by reactGen. DO NOT EDIT.

package react

// ImgProps are the props for a <Img> component
type ImgProps struct {
	Alt                     string
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTML
	DataSet
	ID  string
	Key string

	OnChange
	OnClick

	Ref
	Role  string
	Src   string
	Style *CSS
}

func (i *ImgProps) assign(v *_ImgProps) {

	v.Alt = i.Alt

	v.ClassName = i.ClassName

	v.DangerouslySetInnerHTML = i.DangerouslySetInnerHTML

	if i.DataSet != nil {
		for dk, dv := range i.DataSet {
			v.o.Set("data-"+dk, dv)
		}
	}

	if i.ID != "" {
		v.ID = i.ID
	}

	if i.Key != "" {
		v.Key = i.Key
	}

	if i.OnChange != nil {
		v.o.Set("onChange", i.OnChange.OnChange)
	}

	if i.OnClick != nil {
		v.o.Set("onClick", i.OnClick.OnClick)
	}

	if i.Ref != nil {
		v.o.Set("ref", i.Ref.Ref)
	}

	v.Role = i.Role

	v.Src = i.Src

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	v.Style = i.Style.hack()

}
