// Code generated by reactGen. DO NOT EDIT.

package react

// APropsDef defines the properties for the <a> element
type AProps struct {
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTMLDef
	Href                    string
	ID                      string
	Key                     string
	OnChange                func(e *SyntheticEvent)
	OnClick                 func(e *SyntheticMouseEvent)
	Role                    string
	Style                   *CSS
	Target                  string
}

func (a *AProps) assign(v *_AProps) {

	v.ClassName = a.ClassName

	v.DangerouslySetInnerHTML = a.DangerouslySetInnerHTML

	v.Href = a.Href

	if a.ID != "" {
		v.ID = a.ID
	}

	if a.Key != "" {
		v.Key = a.Key
	}

	v.OnChange = a.OnChange

	v.OnClick = a.OnClick

	v.Role = a.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	v.Style = a.Style.hack()

	v.Target = a.Target

}
