// Code generated by reactGen. DO NOT EDIT.

package react

// DivProps are the props for a <div> component
type DivProps struct {
	ID                      string
	Key                     string
	ClassName               string
	Role                    string
	Style                   *CSS
	OnChange                func(e *SyntheticEvent)
	OnClick                 func(e *SyntheticMouseEvent)
	DangerouslySetInnerHTML *DangerousInnerHTMLDef
}

func (d *DivProps) assign(v *_DivProps) {

	if d.ID != "" {
		v.ID = d.ID
	}

	if d.Key != "" {
		v.Key = d.Key
	}

	v.ClassName = d.ClassName

	v.Role = d.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	v.Style = d.Style.hack()

	v.OnChange = d.OnChange

	v.OnClick = d.OnClick

	v.DangerouslySetInnerHTML = d.DangerouslySetInnerHTML

}
