// Code generated by reactGen. DO NOT EDIT.

package react

// LabelProps defines the properties for the <label> element
type LabelProps struct {
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTML
	DataSet
	For string
	ID  string
	Key string

	OnChange
	OnClick

	Ref
	Role  string
	Style *CSS
}

func (l *LabelProps) assign(_v *_LabelProps) {

	_v.ClassName = l.ClassName

	_v.DangerouslySetInnerHTML = l.DangerouslySetInnerHTML

	if l.DataSet != nil {
		for dk, dv := range l.DataSet {
			_v.o.Set("data-"+dk, dv)
		}
	}

	_v.For = l.For

	if l.ID != "" {
		_v.ID = l.ID
	}

	if l.Key != "" {
		_v.Key = l.Key
	}

	if l.OnChange != nil {
		_v.o.Set("onChange", l.OnChange.OnChange)
	}

	if l.OnClick != nil {
		_v.o.Set("onClick", l.OnClick.OnClick)
	}

	if l.Ref != nil {
		_v.o.Set("ref", l.Ref.Ref)
	}

	_v.Role = l.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	_v.Style = l.Style.hack()

}
