// Code generated by reactGen. DO NOT EDIT.

package react

// CodeProps defines the properties for the <code> element
type CodeProps struct {
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTMLDef
	ID                      string
	Key                     string
	OnChange                func(e *SyntheticEvent)
	OnClick                 func(e *SyntheticMouseEvent)
	Role                    string
	Style                   *CSS
}

func (c *CodeProps) assign(v *_CodeProps) {

	v.ClassName = c.ClassName

	v.DangerouslySetInnerHTML = c.DangerouslySetInnerHTML

	if c.ID != "" {
		v.ID = c.ID
	}

	if c.Key != "" {
		v.Key = c.Key
	}

	v.OnChange = c.OnChange

	v.OnClick = c.OnClick

	v.Role = c.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	v.Style = c.Style.hack()

}
