// Code generated by reactGen. DO NOT EDIT.

package react

// HrProps defines the properties for the <hr> element
type HrProps struct {
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTML
	DataSet
	ID  string
	Key string

	OnChange
	OnClick

	Ref
	Role  string
	Style *CSS
}

func (h *HrProps) assign(_v *_HrProps) {

	_v.ClassName = h.ClassName

	_v.DangerouslySetInnerHTML = h.DangerouslySetInnerHTML

	if h.DataSet != nil {
		for dk, dv := range h.DataSet {
			_v.o.Set("data-"+dk, dv)
		}
	}

	if h.ID != "" {
		_v.ID = h.ID
	}

	if h.Key != "" {
		_v.Key = h.Key
	}

	if h.OnChange != nil {
		_v.o.Set("onChange", h.OnChange.OnChange)
	}

	if h.OnClick != nil {
		_v.o.Set("onClick", h.OnClick.OnClick)
	}

	if h.Ref != nil {
		_v.o.Set("ref", h.Ref.Ref)
	}

	_v.Role = h.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	_v.Style = h.Style.hack()

}
