// Code generated by reactGen. DO NOT EDIT.

package react

// FormProps defines the properties for the <form> element
type FormProps struct {
	ID                      string
	Key                     string
	ClassName               string
	Role                    string
	OnChange                func(e *SyntheticEvent)
	OnClick                 func(e *SyntheticMouseEvent)
	DangerouslySetInnerHTML *DangerousInnerHTMLDef
}

func (f *FormProps) assign(v *_FormProps) {

	if f.ID != "" {
		v.ID = f.ID
	}

	if f.Key != "" {
		v.Key = f.Key
	}

	v.ClassName = f.ClassName

	v.Role = f.Role

	v.OnChange = f.OnChange

	v.OnClick = f.OnClick

	v.DangerouslySetInnerHTML = f.DangerouslySetInnerHTML

}
