// Code generated by reactGen. DO NOT EDIT.

package react

// InputProps defines the properties for the <input> element
type InputProps struct {
	AriaSet
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTML
	DataSet
	DefaultValue string
	ID           string
	Key          string

	OnChange
	OnClick

	Placeholder string
	Ref
	Role  string
	Style *CSS
	Type  string
	Value string
}

func (i *InputProps) assign(_v *_InputProps) {

	if i.AriaSet != nil {
		for dk, dv := range i.AriaSet {
			_v.o.Set("aria-"+dk, dv)
		}
	}

	_v.ClassName = i.ClassName

	_v.DangerouslySetInnerHTML = i.DangerouslySetInnerHTML

	if i.DataSet != nil {
		for dk, dv := range i.DataSet {
			_v.o.Set("data-"+dk, dv)
		}
	}

	if i.DefaultValue != "" {
		_v.DefaultValue = i.DefaultValue
	}

	if i.ID != "" {
		_v.ID = i.ID
	}

	if i.Key != "" {
		_v.Key = i.Key
	}

	if i.OnChange != nil {
		_v.o.Set("onChange", i.OnChange.OnChange)
	}

	if i.OnClick != nil {
		_v.o.Set("onClick", i.OnClick.OnClick)
	}

	_v.Placeholder = i.Placeholder

	if i.Ref != nil {
		_v.o.Set("ref", i.Ref.Ref)
	}

	_v.Role = i.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	_v.Style = i.Style.hack()

	_v.Type = i.Type

	_v.Value = i.Value

}
