// Code generated by reactGen. DO NOT EDIT.

package react

// LiProps defines the properties for the <li> element
type LiProps struct {
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTMLDef
	ID                      string
	Key                     string
	OnChange                func(e *SyntheticEvent)
	OnClick                 func(e *SyntheticMouseEvent)
	Role                    string
	Style                   *CSS
}

func (l *LiProps) assign(v *_LiProps) {

	v.ClassName = l.ClassName

	v.DangerouslySetInnerHTML = l.DangerouslySetInnerHTML

	if l.ID != "" {
		v.ID = l.ID
	}

	if l.Key != "" {
		v.Key = l.Key
	}

	v.OnChange = l.OnChange

	v.OnClick = l.OnClick

	v.Role = l.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	v.Style = l.Style.hack()

}
