// Code generated by reactGen. DO NOT EDIT.

package react

// NavProps defines the properties for the <nav> element
type NavProps struct {
	ID                      string
	Key                     string
	ClassName               string
	Role                    string
	OnChange                func(e *SyntheticEvent)
	OnClick                 func(e *SyntheticMouseEvent)
	DangerouslySetInnerHTML *DangerousInnerHTMLDef
}

func (n *NavProps) assign(v *_NavProps) {

	if n.ID != "" {
		v.ID = n.ID
	}

	if n.Key != "" {
		v.Key = n.Key
	}

	v.ClassName = n.ClassName

	v.Role = n.Role

	v.OnChange = n.OnChange

	v.OnClick = n.OnClick

	v.DangerouslySetInnerHTML = n.DangerouslySetInnerHTML

}
