// Code generated by reactGen; DO NOT EDIT.

package react

// LiProps defines the properties for the <li> element
type LiProps struct {
	ID                      string
	Key                     string
	ClassName               string
	Role                    string
	OnChange                func(e *SyntheticEvent)
	OnClick                 func(e *SyntheticMouseEvent)
	DangerouslySetInnerHTML *DangerousInnerHTMLDef
}

func (l *LiProps) assign(v *_LiProps) {

	if l.ID != "" {
		v.ID = l.ID
	}

	if l.Key != "" {
		v.Key = l.Key
	}

	v.ClassName = l.ClassName

	v.Role = l.Role

	v.OnChange = l.OnChange

	v.OnClick = l.OnClick

	v.DangerouslySetInnerHTML = l.DangerouslySetInnerHTML

}
