// Code generated by reactGen; DO NOT EDIT.

package react

// ButtonProps defines the properties for the <button> element
type ButtonProps struct {
	ID                      string
	Key                     string
	ClassName               string
	Role                    string
	OnChange                func(e *SyntheticEvent)
	OnClick                 func(e *SyntheticMouseEvent)
	DangerouslySetInnerHTML *DangerousInnerHTMLDef
	Type                    string
}

func (b *ButtonProps) assign(v *_ButtonProps) {

	if b.ID != "" {
		v.ID = b.ID
	}

	if b.Key != "" {
		v.Key = b.Key
	}

	v.ClassName = b.ClassName

	v.Role = b.Role

	v.OnChange = b.OnChange

	v.OnClick = b.OnClick

	v.DangerouslySetInnerHTML = b.DangerouslySetInnerHTML

	v.Type = b.Type

}
