// Template generated by reactGen

package main

import (
	"myitcv.io/react"
)

type AppDef struct {
	react.ComponentDef
}

func App() *AppElem {
	return buildAppElem()
}

func (a AppDef) Render() react.Element {
	return react.Div(nil,
		react.H1(nil,
			react.S("Hello World"),
		),
		react.P(nil,
			react.S("This is my first GopherJS React App."),
		),
		FooBar(FooBarProps{Name: "Peter"}),
	)
}
