// Code generated by reactGen. DO NOT EDIT.

package imm

import "myitcv.io/react"

func (s *SelectDef) ShouldComponentUpdateIntf(nextProps, prevState, nextState interface{}) bool {
	res := false

	{
		res = s.Props() != nextProps.(SelectProps) || res
	}
	v := prevState.(SelectState)
	res = !v.EqualsIntf(nextState) || res
	return res
}

// SetState is an auto-generated proxy proxy to update the state for the
// Select component.  SetState does not immediately mutate s.State()
// but creates a pending state transition.
func (s *SelectDef) SetState(state SelectState) {
	s.ComponentDef.SetState(state)
}

// State is an auto-generated proxy to return the current state in use for the
// render of the Select component
func (s *SelectDef) State() SelectState {
	return s.ComponentDef.State().(SelectState)
}

// IsState is an auto-generated definition so that SelectState implements
// the myitcv.io/react.State interface.
func (s SelectState) IsState() {}

var _ react.State = SelectState{}

// GetInitialStateIntf is an auto-generated proxy to GetInitialState
func (s *SelectDef) GetInitialStateIntf() react.State {
	return SelectState{}
}

func (s SelectState) EqualsIntf(val interface{}) bool {
	return s == val.(SelectState)
}

// Props is an auto-generated proxy to the current props of Select
func (s *SelectDef) Props() SelectProps {
	uprops := s.ComponentDef.Props()
	return uprops.(SelectProps)
}

// ComponentWillReceivePropsIntf is an auto-generated proxy to
// ComponentWillReceiveProps
func (s *SelectDef) ComponentWillReceivePropsIntf(val interface{}) {
	ourProps := val.(SelectProps)
	s.ComponentWillReceiveProps(ourProps)
}

func (s SelectProps) EqualsIntf(val interface{}) bool {
	return s == val.(SelectProps)
}

var _ react.Equals = SelectProps{}
