// Code generated by immutableGen. DO NOT EDIT.

package examples

//immutableVet:skipFile

import (
	"myitcv.io/immutable"
)

//
// tabS is an immutable type and has the following template:
//
// 	map[exampleKey]tab
//
type tabS struct {
	theMap  map[exampleKey]tab
	mutable bool
	__tmpl  _Imm_tabS
}

var _ immutable.Immutable = new(tabS)
var _ = new(tabS).__tmpl

func newTabS(inits ...func(m *tabS)) *tabS {
	res := newTabSCap(0)
	if len(inits) == 0 {
		return res
	}

	return res.WithMutable(func(m *tabS) {
		for _, i := range inits {
			i(m)
		}
	})
}

func newTabSCap(l int) *tabS {
	return &tabS{
		theMap: make(map[exampleKey]tab, l),
	}
}

func (m *tabS) Mutable() bool {
	return m.mutable
}

func (m *tabS) Len() int {
	if m == nil {
		return 0
	}

	return len(m.theMap)
}

func (m *tabS) Get(k exampleKey) (tab, bool) {
	v, ok := m.theMap[k]
	return v, ok
}

func (m *tabS) AsMutable() *tabS {
	if m == nil {
		return nil
	}

	if m.Mutable() {
		return m
	}

	res := m.dup()
	res.mutable = true

	return res
}

func (m *tabS) dup() *tabS {
	resMap := make(map[exampleKey]tab, len(m.theMap))

	for k := range m.theMap {
		resMap[k] = m.theMap[k]
	}

	res := &tabS{
		theMap: resMap,
	}

	return res
}

func (m *tabS) AsImmutable(v *tabS) *tabS {
	if m == nil {
		return nil
	}

	if v == m {
		return m
	}

	m.mutable = false
	return m
}

func (m *tabS) Range() map[exampleKey]tab {
	if m == nil {
		return nil
	}

	return m.theMap
}

func (m *tabS) WithMutable(f func(mi *tabS)) *tabS {
	res := m.AsMutable()
	f(res)
	res = res.AsImmutable(m)

	return res
}

func (m *tabS) WithImmutable(f func(mi *tabS)) *tabS {
	prev := m.mutable
	m.mutable = false
	f(m)
	m.mutable = prev

	return m
}

func (m *tabS) Set(k exampleKey, v tab) *tabS {
	if m.mutable {
		m.theMap[k] = v
		return m
	}

	res := m.dup()
	res.theMap[k] = v

	return res
}

func (m *tabS) Del(k exampleKey) *tabS {
	if _, ok := m.theMap[k]; !ok {
		return m
	}

	if m.mutable {
		delete(m.theMap, k)
		return m
	}

	res := m.dup()
	delete(res.theMap, k)

	return res
}
func (s *tabS) IsDeeplyNonMutable(seen map[interface{}]bool) bool {
	if s == nil {
		return true
	}

	if s.Mutable() {
		return false
	}
	return true
}
