package examples

import (
	"honnef.co/go/js/xhr"
	r "myitcv.io/react"
)

// GlobalStateExamplesDef is the definition of the GlobalStateExamples component
type GlobalStateExamplesDef struct {
	r.ComponentDef
}

// GlobalStateExamples creates instances of the GlobalStateExamples component
func GlobalStateExamples() *GlobalStateExamplesElem {
	return buildGlobalStateExamplesElem()
}

// GlobalStateExamplesState is the state type for the GlobalStateExamples component
type GlobalStateExamplesState struct {
	examples     *exampleSource
	selectedTabs *tabS
}

// ComponentWillMount is a React lifecycle method for the GlobalStateExamples component
func (p GlobalStateExamplesDef) ComponentWillMount() {
	if !fetchStarted {
		for i, e := range sources.Range() {
			go func(i exampleKey, e *source) {
				req := xhr.NewRequest("GET", "https://raw.githubusercontent.com/myitcv/react/master/examples/"+e.file())
				err := req.Send(nil)
				if err != nil {
					panic(err)
				}

				sources = sources.Set(i, e.setSrc(req.ResponseText))

				newSt := p.State()
				newSt.examples = sources
				p.SetState(newSt)
			}(i, e)
		}

		fetchStarted = true
	}
}

// GetInitialState returns in the initial state for the GlobalStateExamples component
func (p GlobalStateExamplesDef) GetInitialState() GlobalStateExamplesState {
	return GlobalStateExamplesState{
		examples:     sources,
		selectedTabs: newTabS(),
	}
}

// Render renders the GlobalStateExamples component
func (p GlobalStateExamplesDef) Render() r.Element {

	return r.Div(&r.DivProps{ClassName: "container"},
		r.Div(&r.DivProps{DangerouslySetInnerHTML: r.NewDangerousInnerHTML(`
		<h3>Introduction</h3>

		<p>State can be local to components; we can share that state with descendent components
		by passing props.</p>

		<p>But this can either lead to passing around a lot of props, or not be possible at all because
		two components are in very different parts of the component (ultimately DOM) tree.</p>

		<p>State trees generated by <a href="https://github.com/myitcv/react/tree/master/cmd/stateGen">
		<code>stateGen</code></a> exist to fill this gap.</p>

		<p>This example is best considered as a standalone web app (because the state tree is effectively)
		a global in the application).</p>

		<p><a role="button" href="../globalstate" target="_blank" class="btn btn-primary">Launch Example</a></p>

		<p>The source code for the example that follows can be found <a href="https://github.com/myitcv/react/tree/master/examples/globalstate">
		Github repo</a>.
		`)}),
	)
}
