// Do not edit: file generated by reactGen

package hellomessage

// Props is an auto-generated proxy to the current props of HelloMessage
func (h *HelloMessageDef) Props() HelloMessageProps {
	uprops := h.ComponentDef.Props()
	return uprops.(HelloMessageProps)
}
