// Code generated by reactGen; DO NOT EDIT.

package hellomessage

import "github.com/myitcv/gopherjs/react"

func (h *HelloMessageDef) ShouldComponentUpdateIntf(nextProps interface{}) bool {
	return h.Props() == nextProps.(HelloMessageProps)
}

// Props is an auto-generated proxy to the current props of HelloMessage
func (h *HelloMessageDef) Props() HelloMessageProps {
	uprops := h.ComponentDef.Props()
	return uprops.(HelloMessageProps)
}

func (h HelloMessageProps) EqualsIntf(v interface{}) bool {
	return h == v.(HelloMessageProps)
}

var _ react.Equals = HelloMessageProps{}
