// Do not edit: file generated by reactGen

package main

import "github.com/myitcv/gopherjs/react"

func (p *ExamplesDef) SetState(s ExamplesState) {
	p.ComponentDef.SetState(s)
}

func (p *ExamplesDef) State() ExamplesState {
	return p.ComponentDef.State().(ExamplesState)
}

func (p ExamplesState) IsState() {}

func (p *ExamplesDef) GetInitialStateIntf() react.State {
	return p.GetInitialState()
}
