// Code generated by reactGen; DO NOT EDIT.

package examples

import "github.com/myitcv/gopherjs/react"

func (i *ImmExamplesDef) ShouldComponentUpdateIntf(nextProps interface{}) bool {
	return true
}

// SetState is an auto-generated proxy proxy to update the state for the
// ImmExamples component.  SetState does not immediately mutate i.State()
// but creates a pending state transition.
func (i *ImmExamplesDef) SetState(s ImmExamplesState) {
	i.ComponentDef.SetState(s)
}

// State is an auto-generated proxy to return the current state in use for the
// render of the ImmExamples component
func (i *ImmExamplesDef) State() ImmExamplesState {
	return i.ComponentDef.State().(ImmExamplesState)
}

// IsState is an auto-generated definition so that ImmExamplesState implements
// the github.com/myitcv/gopherjs/react.State interface.
func (i ImmExamplesState) IsState() {}

var _ react.State = ImmExamplesState{}

// GetInitialStateIntf is an auto-generated proxy to GetInitialState
func (i *ImmExamplesDef) GetInitialStateIntf() react.State {
	return i.GetInitialState()
}

func (i ImmExamplesState) EqualsIntf(v interface{}) bool {
	return i == v.(ImmExamplesState)
}
