// Code generated by reactGen. DO NOT EDIT.

package html

// BRProps defines the properties for the <br> element
type BRProps struct {
	*BasicHTMLElement
}

func (b *BRProps) assign(v *_BRProps) {

	v.BasicHTMLElement = b.BasicHTMLElement

}
