// Code generated by reactGen. DO NOT EDIT.

package html

// OptionProps defines the properties for the <option> element
type OptionProps struct {
	*BasicHTMLElement
	Value string
}

func (o *OptionProps) assign(v *_OptionProps) {

	v.BasicHTMLElement = o.BasicHTMLElement

	v.Value = o.Value

}
