// Code generated by reactGen. DO NOT EDIT.

package html

// H1Props defines the properties for the <h1> element
type H1Props struct {
	*BasicHTMLElement
}

func (h *H1Props) assign(v *_H1Props) {

	v.BasicHTMLElement = h.BasicHTMLElement

}
