// Code generated by reactGen. DO NOT EDIT.

package html

// TextAreaProps defines the properties for the <textarea> element
type TextAreaProps struct {
	*BasicHTMLElement
	Cols         uint
	DefaultValue string
	Placeholder  string
	Rows         uint
	Value        string
}

func (t *TextAreaProps) assign(v *_TextAreaProps) {

	v.BasicHTMLElement = t.BasicHTMLElement

	v.Cols = t.Cols

	if t.DefaultValue != "" {
		v.DefaultValue = t.DefaultValue
	}

	v.Placeholder = t.Placeholder

	v.Rows = t.Rows

	v.Value = t.Value

}
