// Code generated by reactGen. DO NOT EDIT.

package html

// H3Props defines the properties for the <h3> element
type H3Props struct {
	*BasicHTMLElement
}

func (h *H3Props) assign(v *_H3Props) {

	v.BasicHTMLElement = h.BasicHTMLElement

}
