// Code generated by reactGen. DO NOT EDIT.

package html

// PreProps defines the properties for the <pre> element
type PreProps struct {
	*BasicHTMLElement
}

func (p *PreProps) assign(v *_PreProps) {

	v.BasicHTMLElement = p.BasicHTMLElement

}
