// Code generated by reactGen. DO NOT EDIT.

package html

// SpanProps defines the properties for the <p> element
type SpanProps struct {
	*BasicHTMLElement
}

func (s *SpanProps) assign(v *_SpanProps) {

	v.BasicHTMLElement = s.BasicHTMLElement

}
