// Code generated by reactGen. DO NOT EDIT.

package html

// ImgProps are the props for a <Img> component
type ImgProps struct {
	*BasicHTMLElement
	Src string
}

func (i *ImgProps) assign(v *_ImgProps) {

	v.BasicHTMLElement = i.BasicHTMLElement

	v.Src = i.Src

}
