// Code generated by reactGen. DO NOT EDIT.

package html

// UlProps defines the properties for the <ul> element
type UlProps struct {
	*BasicHTMLElement
}

func (u *UlProps) assign(v *_UlProps) {

	v.BasicHTMLElement = u.BasicHTMLElement

}
