// Code generated by reactGen. DO NOT EDIT.

package html

// LiProps defines the properties for the <li> element
type LiProps struct {
	*BasicHTMLElement
}

func (l *LiProps) assign(v *_LiProps) {

	v.BasicHTMLElement = l.BasicHTMLElement

}
