// Code generated by reactGen. DO NOT EDIT.

package html

// LabelProps defines the properties for the <label> element
type LabelProps struct {
	*BasicHTMLElement
	For string
}

func (l *LabelProps) assign(v *_LabelProps) {

	v.BasicHTMLElement = l.BasicHTMLElement

	v.For = l.For

}
