// Code generated by reactGen. DO NOT EDIT.

package html

// FooterProps are the props for a <footer> component
type FooterProps struct {
	*BasicHTMLElement
}

func (f *FooterProps) assign(v *_FooterProps) {

	v.BasicHTMLElement = f.BasicHTMLElement

}
