// Code generated by reactGen. DO NOT EDIT.

package html

// InputProps defines the properties for the <input> element
type InputProps struct {
	*BasicHTMLElement
	DefaultValue string
	Placeholder  string
	Type         string
	Value        string
}

func (i *InputProps) assign(v *_InputProps) {

	v.BasicHTMLElement = i.BasicHTMLElement

	if i.DefaultValue != "" {
		v.DefaultValue = i.DefaultValue
	}

	v.Placeholder = i.Placeholder

	v.Type = i.Type

	v.Value = i.Value

}
