// Code generated by reactGen. DO NOT EDIT.

package html

// HRProps defines the properties for the <hr> element
type HRProps struct {
	*BasicHTMLElement
}

func (h *HRProps) assign(v *_HRProps) {

	v.BasicHTMLElement = h.BasicHTMLElement

}
