// Code generated by reactGen. DO NOT EDIT.

package html

// CodeProps defines the properties for the <code> element
type CodeProps struct {
	*BasicHTMLElement
}

func (c *CodeProps) assign(v *_CodeProps) {

	v.BasicHTMLElement = c.BasicHTMLElement

}
