// Code generated by reactGen. DO NOT EDIT.

package html

// FormProps defines the properties for the <form> element
type FormProps struct {
	*BasicHTMLElement
}

func (f *FormProps) assign(v *_FormProps) {

	v.BasicHTMLElement = f.BasicHTMLElement

}
