// Code generated by reactGen. DO NOT EDIT.

package html

// PProps are the props for a <div> component
type PProps struct {
	*BasicHTMLElement
}

func (p *PProps) assign(v *_PProps) {

	v.BasicHTMLElement = p.BasicHTMLElement

}
