// Code generated by reactGen. DO NOT EDIT.

package html

// DivProps are the props for a <div> component
type DivProps struct {
	*BasicHTMLElement
}

func (d *DivProps) assign(v *_DivProps) {

	v.BasicHTMLElement = d.BasicHTMLElement

}
