// Code generated by reactGen. DO NOT EDIT.

package html

import "myitcv.io/react/dom"

// FormProps defines the properties for the <form> element
type FormProps struct {
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTML
	ID                      string
	Key                     string
	OnChange                dom.OnChange
	OnClick                 dom.OnClick
	Role                    string
	Style                   *CSS
}

func (f *FormProps) assign(v *_FormProps) {

	v.ClassName = f.ClassName

	v.DangerouslySetInnerHTML = f.DangerouslySetInnerHTML

	if f.ID != "" {
		v.ID = f.ID
	}

	if f.Key != "" {
		v.Key = f.Key
	}

	v.OnChange = f.OnChange

	v.OnClick = f.OnClick

	v.Role = f.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	v.Style = f.Style.hack()

}
