// Code generated by reactGen. DO NOT EDIT.

package html

// H4Props defines the properties for the <h4> element
type H4Props struct {
	*BasicHTMLElement
}

func (h *H4Props) assign(v *_H4Props) {

	v.BasicHTMLElement = h.BasicHTMLElement

}
