// Code generated by reactGen. DO NOT EDIT.

package html

// IProps are the props for a <i> component
type IProps struct {
	*BasicHTMLElement
	Src string
}

func (i *IProps) assign(v *_IProps) {

	v.BasicHTMLElement = i.BasicHTMLElement

	v.Src = i.Src

}
