// Code generated by reactGen. DO NOT EDIT.

package html

// NavProps defines the properties for the <nav> element
type NavProps struct {
	*BasicHTMLElement
}

func (n *NavProps) assign(v *_NavProps) {

	v.BasicHTMLElement = n.BasicHTMLElement

}
