// Code generated by reactGen. DO NOT EDIT.

package html

// ButtonProps defines the properties for the <button> element
type ButtonProps struct {
	*BasicHTMLElement
	Type string
}

func (b *ButtonProps) assign(v *_ButtonProps) {

	v.BasicHTMLElement = b.BasicHTMLElement

	v.Type = b.Type

}
