// Code generated by reactGen. DO NOT EDIT.

package html

// SelectProps are the props for a <select> component
type SelectProps struct {
	*BasicHTMLElement
	Value string
}

func (s *SelectProps) assign(v *_SelectProps) {

	v.BasicHTMLElement = s.BasicHTMLElement

	v.Value = s.Value

}
