// Code generated by reactGen. DO NOT EDIT.

package html

// APropsDef defines the properties for the <a> element
type AProps struct {
	*BasicHTMLElement
	Href   string
	Target string
}

func (a *AProps) assign(v *_AProps) {

	v.BasicHTMLElement = a.BasicHTMLElement

	v.Href = a.Href

	v.Target = a.Target

}
