// Copyright (c) 2016 Paul Jolly <paul@myitcv.org.uk>, all rights reserved.
// Use of this document is governed by a license found in the LICENSE document.

package main

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/printer"
	"go/token"
	"io/ioutil"
	"sort"
	"strings"
	"unicode/utf8"

	"myitcv.io/gogenerate"
)

const (
	reactPkg      = "myitcv.io/react"
	compDefName   = "ComponentDef"
	compDefSuffix = "Def"

	stateTypeSuffix     = "State"
	propsTypeSuffix     = "Props"
	propsTypeTmplPrefix = "_"

	getInitialState           = "GetInitialState"
	componentWillReceiveProps = "ComponentWillReceiveProps"
	equals                    = "Equals"
)

type typeFile struct {
	ts   *ast.TypeSpec
	file *ast.File
}

type funcFile struct {
	fn   *ast.FuncDecl
	file *ast.File
}

var fset = token.NewFileSet()

func astNodeString(i interface{}) string {
	b := bytes.NewBuffer(nil)
	err := printer.Fprint(b, fset, i)
	if err != nil {
		fatalf("failed to astNodeString %v: %v", i, err)
	}

	return b.String()
}

func lowerInitial(s string) string {
	if s == "" {
		return ""
	}

	r, w := utf8.DecodeRuneInString(s)
	return strings.ToLower(string(r)) + s[w:]
}

func dogen(dir, pkgName, license string) {
	cg := newCoreGen()

	// fill out templates
	for _, t := range templates {
		for n, a := range t {
			a.Name = n
			if a.React == "" {
				a.React = lowerInitial(n)
			}
			if a.Type == "" {
				a.Type = "string"
			}
		}
	}

	// fill out elements
	for n, e := range elements {
		e.Name = n
		if e.React == "" {
			e.React = strings.ToLower(n)
		}
		if !e.NonHTML {
			e.Templates = append(e.Templates, "html")
		}
		if e.EmptyElement && (e.Child != "" || e.Children != "") {
			fatalf("element %v specified as EmptyElement but also child or children properties", e.Name)
		}
		if e.Child != "" && e.Children != "" {
			fatalf("element %v supplied both child and children properties", e.Name)
		}
		if !e.EmptyElement && e.Children == "" {
			e.Children = "Element"
		}
		if e.Dom == "" {
			e.Dom = "HTML" + e.Name + "Element"
		}
		for n, a := range e.Attributes {
			a.Name = n
			if a.React == "" {
				a.React = lowerInitial(n)
			}
			if a.Type == "" {
				a.Type = "string"
			}
		}
	}

	var ens []string

	// generate elements
	for _, e := range elements {
		ens = append(ens, e.Name)
		attrs := make(map[string]*Attr)
		addAttr := func(n string, a *Attr) {
			if _, ok := attrs[n]; ok {
				fatalf("element %v had a clash for attribute %v", e.Name, n)
			}
			attrs[n] = a
		}

		for _, tn := range e.Templates {
			t, ok := templates[tn]
			if !ok {
				fatalf("element %v referenced non-existent template %q", e.Name, tn)
			}
			for _, a := range t {
				addAttr(a.Name, a)
			}
		}

		for _, a := range e.Attributes {
			addAttr(a.Name, a)
		}

		e.Attributes = attrs
	}

	sort.Strings(ens)

	// regular header
	cg.pf("// Code generated by %v. DO NOT EDIT.\n", coreGenCmd)
	cg.pln()
	cg.pf("package %v\n", pkgName)
	cg.pln()
	cg.pln(`import "github.com/gopherjs/gopherjs/js"`)

	// test header
	cg.tpln("// +build js")
	cg.tpln()
	cg.tpf("// Code generated by %v. DO NOT EDIT.\n", coreGenCmd)
	cg.tpln()
	cg.tpf("package %v_test\n", pkgName)
	cg.tpln(`
import (
	"testing"

	"honnef.co/go/js/dom"

	"myitcv.io/react"
	"myitcv.io/react/testutils"
)
	`)

	for _, en := range ens {
		e := elements[en]
		cg.pt(`
{{$elem := .}}

// {{.Name}}Elem is the React element definition corresponding to the HTML <{{.React}}> element
type {{.Name}}Elem struct {
	Element
}

func (a *{{.Name}}Elem) coreReactElement() {}

{{range .Implements}}
func (l *{{$elem.Name}}Elem) {{.}} {}
{{end}}

// _AProps defines the properties for the <a> element
type {{.Name}}Props struct {
	{{- range .Attributes}}
	{{.Name}} {{.Type -}}
	{{end}}
}

// {{.Name}} creates a new instance of a <{{.React}}> element with the provided props and
// children
func {{.Name}}(props *{{.Name}}Props, {{.ChildParam}}) *{{.Name}}Elem {
	type _{{.Name}}Props struct {
		o *js.Object
		{{- range .Attributes}}
		{{- if not .NoJS}}
		{{.Name}} {{.Type}} {{.Tag -}}
		{{end -}}
		{{end}}
	}

	{{.ChildConvert}}

	rprops := &_{{.Name}}Props{
		o: object.New(),
	}

	if props != nil {
		{{- range .Attributes}}
			{{- if eq .Name "Ref" }}
			if props.Ref != nil {
				rprops.o.Set("ref", props.Ref.Ref)
			}
			{{- else if eq .Name "DataSet" }}
			if props.DataSet != nil {
				for dk, dv := range props.DataSet {
					rprops.o.Set("data-"+dk, dv)
				}
			}
			{{- else if eq .Name "AriaSet" }}
			if props.AriaSet != nil {
				for dk, dv := range props.AriaSet {
					rprops.o.Set("aria-"+dk, dv)
				}
			}
			{{- else}}
			{{- if .OmitEmpty }}
				if props.{{.Name}} != "" {
					rprops.{{.Name}} = props.{{.Name}}
				}
			{{- else}}
			{{- if .IsEvent}}
				if props.{{.Name}} != nil {
					rprops.o.Set("{{.React}}", props.{{.Name}}.{{.Name}})
				}
			{{- else if eq .Name "Style"}}
				// TODO: until we have a resolution on
				// https://github.com/gopherjs/gopherjs/issues/236
				rprops.{{.Name}} = props.{{.Name}}.hack()
			{{- else}}
				rprops.{{.Name}} = props.{{.Name}}
			{{end -}}
			{{end -}}
			{{end -}}
		{{end -}}
	}

	return &{{.Name}}Elem{
		Element: createElement("{{.React}}", rprops, {{.ChildArg}}),
	}
}
		`, e)

		if e.SkipTests {
			continue
		}

		cg.tpt(`
func Test{{.Name}}Elem(t *testing.T) {
	class := "test"

	x := testutils.Wrapper(react.{{.Name}}(&react.{{.Name}}Props{ClassName: class}))
	cont := testutils.RenderIntoDocument(x)

	el := testutils.FindRenderedDOMComponentWithClass(cont, class)

	if _, ok := el.(*dom.{{.Dom}}); !ok {
		t.Fatal("Failed to find <{{.React}}> element")
	}
}
		`, e)
	}

	write := func(w *bytes.Buffer, fn string) {
		toWrite := w.Bytes()

		out, err := format.Source(toWrite)
		if err == nil {
			toWrite = out
		}

		if err := ioutil.WriteFile(fn, toWrite, 0644); err != nil {
			fatalf("failed to write to %v; %v", fn)
		}
	}

	write(cg.buf, gogenerate.NameFile(pkgName, coreGenCmd))
	write(cg.tbuf, gogenerate.NameTestFile(pkgName, coreGenCmd))
}
