// Code generated by reactGen; DO NOT EDIT.

package markdowneditor

import "github.com/myitcv/gopherjs/react"

func (m *MarkdownEditorDef) ShouldComponentUpdateIntf(nextProps interface{}) bool {
	return true
}

// SetState is an auto-generated proxy proxy to update the state for the
// MarkdownEditor component.  SetState does not immediately mutate m.State()
// but creates a pending state transition.
func (m *MarkdownEditorDef) SetState(s MarkdownEditorState) {
	m.ComponentDef.SetState(s)
}

// State is an auto-generated proxy to return the current state in use for the
// render of the MarkdownEditor component
func (m *MarkdownEditorDef) State() MarkdownEditorState {
	return m.ComponentDef.State().(MarkdownEditorState)
}

// IsState is an auto-generated definition so that MarkdownEditorState implements
// the github.com/myitcv/gopherjs/react.State interface.
func (m MarkdownEditorState) IsState() {}

var _ react.State = MarkdownEditorState{}

// GetInitialStateIntf is an auto-generated proxy to GetInitialState
func (m *MarkdownEditorDef) GetInitialStateIntf() react.State {
	return m.GetInitialState()
}

func (m MarkdownEditorState) EqualsIntf(v interface{}) bool {
	return m == v.(MarkdownEditorState)
}
