// Do not edit: file generated by reactGen

package timer

import "github.com/myitcv/gopherjs/react"

func (t *TimerDef) ShouldComponentUpdateIntf(nextProps interface{}) bool {
	return true
}

// SetState is an auto-generated proxy proxy to update the state for the
// Timer component.  SetState does not immediately mutate t.State()
// but creates a pending state transition.
func (t *TimerDef) SetState(s TimerState) {
	t.ComponentDef.SetState(s)
}

// State is an auto-generated proxy to return the current state in use for the
// render of the Timer component
func (t *TimerDef) State() TimerState {
	return t.ComponentDef.State().(TimerState)
}

// IsState is an auto-generated definition so that TimerState implements
// the github.com/myitcv/gopherjs/react.State interface.
func (t TimerState) IsState() {}

var _ react.State = TimerState{}

// GetInitialStateIntf is an auto-generated proxy to GetInitialState
func (t *TimerDef) GetInitialStateIntf() react.State {
	return TimerState{}
}

func (t TimerState) EqualsIntf(v interface{}) bool {
	return t == v.(TimerState)
}
