// Do not edit: file generated by reactGen

package timer

import "github.com/myitcv/gopherjs/react"

func (p *TimerDef) SetState(s TimerState) {
	p.ComponentDef.SetState(s)
}

func (p *TimerDef) State() TimerState {
	return p.ComponentDef.State().(TimerState)
}

func (p TimerState) IsState() {}

func (p *TimerDef) GetInitialStateIntf() react.State {
	return TimerState{}
}
